'use client';

import React, { useEffect, useMemo, useState } from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { html as htmlLang } from '@codemirror/lang-html';
import { motion } from 'framer-motion';
import { useUser } from "@stackframe/stack";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

interface EditorWorkspaceProps {
  initialHTML: string;
  initialPrompt: string;
  projectName: string;
  onBack: () => void;
}

export default function EditorWorkspace({ initialHTML, initialPrompt, projectName, onBack }: EditorWorkspaceProps) {
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');
  const [editableHtml, setEditableHtml] = useState(initialHTML);
  const [transformPrompt, setTransformPrompt] = useState('');
  const [isTransforming, setIsTransforming] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved'>('idle');
  const [isPolishDialogOpen, setIsPolishDialogOpen] = useState(false);
  const [polishDescription, setPolishDescription] = useState('images, typography, animations, mobile responsiveness');

  const user = useUser();
  const saveProject = useMutation(api.projects.saveProject);
  const publishProject = useMutation(api.projects.publishProject);
  const projectData = useQuery(api.projects.getProject, { projectName });

  // Auto-save to Convex
  useEffect(() => {
    if (!user || !editableHtml) return;

    const timer = setTimeout(async () => {
      setSaveStatus('saving');
      try {
        await saveProject({
          projectName,
          prompt: initialPrompt,
          html: editableHtml,
          status: 'completed',
          userId: user.id,
          isPublished: projectData?.isPublished ?? false,
        });
        setSaveStatus('saved');
        setTimeout(() => setSaveStatus('idle'), 2000);
      } catch (err) {
        console.error('Auto-save failed', err);
        setSaveStatus('idle');
      }
    }, 2000);

    return () => clearTimeout(timer);
  }, [editableHtml, user, projectName, initialPrompt, saveProject, projectData?.isPublished]);

  const previewHtml = useMemo(() => {
    if (!editableHtml) return '';
    const script = `
      <script>
        document.addEventListener('click', (e) => {
          const a = e.target.closest('a');
          if (a) {
            const href = a.getAttribute('href');
            if (href && href.startsWith('#')) {
              e.preventDefault();
              const target = document.querySelector(href);
              if (target) {
                target.scrollIntoView({ behavior: 'smooth' });
                history.pushState(null, null, href);
              }
            } else if (href && !href.startsWith('javascript:')) {
              e.preventDefault();
              window.open(a.href, '_blank');
            }
          }
        });
      </script>
    `;

    if (/<head[^>]*>/i.test(editableHtml)) {
      return editableHtml.replace(/<head[^>]*>/i, (match) => `${match}\n    ${script}`);
    }
    if (/<body[^>]*>/i.test(editableHtml)) {
      return editableHtml.replace(/<body[^>]*>/i, (match) => `${match}\n    ${script}`);
    }
    return `${script}${editableHtml}`;
  }, [editableHtml]);

  // Sync when initial HTML changes
  useEffect(() => {
    setEditableHtml(initialHTML);
  }, [initialHTML]);

  const downloadZip = async () => {
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      zip.file('index.html', editableHtml);
      zip.file('README.txt', 'Generated by Mini App Factory');
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'site.zip';
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Zip failed', err);
    }
  };

  const runTransform = async () => {
    if (!transformPrompt.trim()) return;
    setIsTransforming(true);
    try {
      const response = await fetch('/api/transform', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: editableHtml, prompt: transformPrompt }),
      });
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Transform failed');
      }
      const data = await response.json();
      setEditableHtml(data.html);
      setTransformPrompt('');
    } catch (err) {
      console.error('Transform error', err);
    } finally {
      setIsTransforming(false);
    }
  };

  const runPolish = () => {
    setIsPolishDialogOpen(true);
  };

  const onPolishSubmit = async () => {
    setIsPolishDialogOpen(false);
    setIsTransforming(true);
    try {
      const resp = await fetch('/api/transform', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: editableHtml, polishDescription }),
      });
      if (!resp.ok) throw new Error('Polish failed');
      const data = await resp.json();
      setEditableHtml(data.html);
    } catch (err) {
      console.error(err);
    } finally {
      setIsTransforming(false);
    }
  };

  const handlePublish = async () => {
    if (!user) {
      window.location.href = '/handler/sign-in';
      return;
    }

    setIsPublishing(true);
    try {
      // First save the latest version
      await saveProject({
        projectName,
        prompt: initialPrompt,
        html: editableHtml,
        status: 'completed',
        userId: user.id,
        isPublished: true,
      });

      // Then explicitly publish
      await publishProject({
        projectName,
        userId: user.id,
      });

      window.open(`/results/${projectName}`, '_blank');
    } catch (err) {
      console.error('Publish failed', err);
      alert('Failed to publish project');
    } finally {
      setIsPublishing(false);
    }
  };

  return (
    <motion.div
      className="flex flex-col h-screen"
      style={{ backgroundColor: 'var(--background)' }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3 }}
    >
      {/* Header */}
      <header
        className="shrink-0 border-b flex flex-col"
        style={{
          backgroundColor: 'var(--background)',
          borderColor: 'var(--border)',
        }}
      >
        {/* Top bar: Navigation & Tabs */}
        <div className="flex items-center justify-between px-4 py-2 border-b" style={{ borderColor: 'var(--border)' }}>
          <div className="flex items-center gap-6">
            <button
              onClick={onBack}
              className="text-xs font-mono uppercase font-bold tracking-widest hover:text-[var(--primary)] transition-colors"
              style={{ color: 'var(--secondary-text)' }}
            >
              ← Back
            </button>
            <div className="flex items-center gap-1 border-l pl-6" style={{ borderColor: 'var(--border)' }}>
              <button
                onClick={() => setActiveTab('preview')}
                className={`px-4 py-1.5 text-[10px] font-mono uppercase font-black transition-all ${
                  activeTab === 'preview' ? 'bg-[var(--primary)] text-black' : 'text-[var(--secondary-text)] hover:text-white'
                }`}
              >
                Preview
              </button>
              <button
                onClick={() => setActiveTab('code')}
                className={`px-4 py-1.5 text-[10px] font-mono uppercase font-black transition-all ${
                  activeTab === 'code' ? 'bg-[var(--primary)] text-black' : 'text-[var(--secondary-text)] hover:text-white'
                }`}
              >
                Code
              </button>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono text-[var(--muted-text)] uppercase tracking-widest hidden sm:block">
              Fabricating:
            </span>
            <span className="text-[10px] font-display font-black uppercase tracking-[0.2em]" style={{ color: 'var(--foreground)' }}>
              {projectName}
            </span>
          </div>
        </div>

        {/* Action bar: Status & Controls */}
        <div className="flex items-center justify-end px-4 py-2 bg-[var(--background-surface)] gap-4">
          <div className="flex-1 flex items-center gap-3">
            <div className="flex items-center gap-2">
              <div className={`w-1.5 h-1.5 rounded-full ${saveStatus === 'saving' ? 'bg-yellow-500 animate-pulse' : 'bg-[var(--primary)]'}`} />
              <span className="text-[9px] font-mono uppercase text-[var(--muted-text)]">
                {saveStatus === 'saving' ? 'Syncing to cloud...' : saveStatus === 'saved' ? 'All changes saved' : 'System Online'}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={downloadZip}
              className="px-4 py-1.5 text-[10px] font-mono uppercase font-bold text-[var(--secondary-text)] border border-[var(--border)] hover:border-[var(--primary)] hover:text-[var(--primary)] transition-all"
            >
              Export ZIP
            </button>
            <button
              onClick={handlePublish}
              disabled={isPublishing}
              className="flex items-center gap-2 px-4 py-1.5 text-[10px] font-mono uppercase font-black bg-[var(--primary)] text-black hover:bg-white transition-all disabled:opacity-50"
            >
              {isPublishing && <svg className="animate-spin h-3 w-3" viewBox="0 0 24 24" fill="none"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/></svg>}
              {isPublishing ? 'Publishing' : 'Publish'}
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Editor Area */}
        <div className="flex-1 overflow-auto">
          {activeTab === 'preview' && (
            <div className="w-full h-full bg-white">
              <iframe
                srcDoc={previewHtml}
                className="w-full h-full border-0"
                sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"
                title="Website Preview"
              />
            </div>
          )}

          {activeTab === 'code' && (
            <div className="w-full h-full flex flex-col overflow-hidden relative" style={{ backgroundColor: 'var(--background-surface)' }}>
              <div className="absolute top-4 right-8 z-10 flex gap-2">
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(editableHtml);
                  }}
                  className="px-3 py-1 text-[9px] font-mono uppercase font-black bg-[var(--background)] border border-[var(--border)] text-[var(--secondary-text)] hover:text-[var(--primary)] hover:border-[var(--primary)] transition-all flex items-center gap-1.5"
                >
                  <svg className="w-2.5 h-2.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
                  Copy
                </button>
                <button
                  onClick={() => {
                    if (confirm('Reset to initial version? All manual changes will be lost.')) {
                      setEditableHtml(initialHTML);
                    }
                  }}
                  className="px-3 py-1 text-[9px] font-mono uppercase font-black bg-[var(--background)] border border-[var(--border)] text-[var(--secondary-text)] hover:text-[var(--error)] hover:border-[var(--error)] transition-all flex items-center gap-1.5"
                >
                  <svg className="w-2.5 h-2.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>
                  Reset
                </button>
              </div>
              <div className="flex-1 overflow-auto pt-0">
                <CodeMirror
                  value={editableHtml}
                  height="100%"
                  extensions={[htmlLang()]}
                  onChange={(value) => setEditableHtml(value)}
                  basicSetup={{
                    highlightActiveLine: true,
                    lineNumbers: true,
                    foldGutter: true,
                    highlightActiveLineGutter: true,
                  }}
                  theme="dark"
                  style={{ height: '100%', fontSize: '12px' }}
                />
              </div>
            </div>
          )}
        </div>

        {/* Sidebar */}
        <aside
          className="w-80 border-l flex flex-col overflow-hidden shrink-0"
          style={{
            backgroundColor: 'var(--background-surface)',
            borderColor: 'var(--border)',
          }}
        >
          {/* Transform Section */}
          <div className="p-4 border-b" style={{ borderColor: 'var(--border)' }}>
            <h3
              className="text-[10px] font-mono uppercase font-black tracking-[0.2em] mb-4"
              style={{ color: 'var(--secondary-text)' }}
            >
              Transform with AI
            </h3>
            <textarea
              value={transformPrompt}
              onChange={(e) => setTransformPrompt(e.target.value)}
              placeholder="Describe changes... (e.g., 'Make the hero purple and add a signup modal')"
              className="w-full h-32 resize-none text-xs p-3 border bg-[var(--background)] focus:outline-none focus:border-[var(--primary)] transition-colors font-mono leading-relaxed"
              style={{
                borderColor: 'var(--border)',
                color: 'var(--foreground)',
              }}
            />
            <div className="flex gap-2 mt-3">
              <button
                onClick={runTransform}
                disabled={isTransforming || !transformPrompt.trim()}
                className="flex-1 px-3 py-2 text-[10px] font-mono uppercase font-black flex items-center justify-center gap-2 transition-all"
                style={{
                  backgroundColor:
                    isTransforming || !transformPrompt.trim() ? 'var(--background)' : 'var(--primary)',
                  color:
                    isTransforming || !transformPrompt.trim()
                      ? 'var(--muted-text)'
                      : 'var(--primary-foreground)',
                  borderColor:
                    isTransforming || !transformPrompt.trim() ? 'var(--border)' : 'var(--primary)',
                  borderWidth: '1px',
                  cursor: isTransforming || !transformPrompt.trim() ? 'not-allowed' : 'pointer',
                }}
              >
                {isTransforming ? (
                  <>
                    <svg className="animate-spin w-3 h-3" viewBox="0 0 24 24" fill="none">
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    Apply
                  </>
                ) : (
                  'Apply'
                )}
              </button>
              <button
                onClick={runPolish}
                disabled={isTransforming}
                className="px-4 py-2 text-[10px] font-mono uppercase font-black border border-[var(--border)] hover:border-white transition-all"
                style={{
                  color: 'var(--foreground)',
                }}
              >
                Polish
              </button>
            </div>
          </div>
        </aside>
      </div>

      <Dialog open={isPolishDialogOpen} onOpenChange={setIsPolishDialogOpen}>
        <DialogContent className="sm:max-w-[425px] bg-[var(--background)] border-[var(--border)] text-[var(--foreground)]">
          <DialogHeader>
            <DialogTitle className="font-mono uppercase text-sm tracking-tight">Polish Site</DialogTitle>
            <DialogDescription className="text-xs text-[var(--muted-text)] font-mono">
              Describe how to polish this site (images, typography, animations, mobile responsiveness).
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <Textarea
              value={polishDescription}
              onChange={(e) => setPolishDescription(e.target.value)}
              className="min-h-[100px] text-xs font-mono bg-[var(--background)] border-[var(--border)] focus-visible:ring-[var(--primary)]"
            />
          </div>
          <DialogFooter className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => setIsPolishDialogOpen(false)}
              className="flex-1 font-mono uppercase text-[10px] border-[var(--border)] text-[var(--foreground)] hover:bg-[var(--background-overlay)]"
            >
              Cancel
            </Button>
            <Button
              onClick={onPolishSubmit}
              className="flex-1 bg-[var(--primary)] hover:bg-[var(--primary)]/90 text-[var(--primary-foreground)] font-mono uppercase text-[10px] font-black"
            >
              Apply Polish
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </motion.div>
  );
}
