'use client';

import React, { useEffect, useState } from 'react';
import CodeMirror from '@uiw/react-codemirror';

interface PreviewPanelProps {
  html: string;
}

export default function PreviewPanel({ html }: PreviewPanelProps) {
  const [showCode, setShowCode] = useState(false);
  const [editableHtml, setEditableHtml] = useState(html);
  const [isEditing, setIsEditing] = useState(false);
  const [savedSites, setSavedSites] = useState<Array<{id:string;name:string;prompt?:string;html:string;createdAt:string}>>([]);
  const [selectedSiteId, setSelectedSiteId] = useState<string | null>(null);
  const [transformPrompt, setTransformPrompt] = useState('');
  const [isTransforming, setIsTransforming] = useState(false);

  // Sync editable html when parent prop changes
  useEffect(() => {
    setEditableHtml(html);
  }, [html]);

  useEffect(() => {
    const raw = localStorage.getItem('mini_app_factory_sites');
    if (raw) {
      try {
        setSavedSites(JSON.parse(raw));
      } catch (e) {
        console.error('Failed to parse saved sites', e);
      }
    }
  }, []);

  const persistSites = (sites: typeof savedSites) => {
    setSavedSites(sites);
    localStorage.setItem('mini_app_factory_sites', JSON.stringify(sites));
  };

  const saveCurrentSite = (name?:string) => {
    if (!editableHtml) return;
    const id = Date.now().toString();
    const site = {
      id,
      name: name || `Site ${new Date().toLocaleString()}`,
      prompt: transformPrompt || '',
      html: editableHtml,
      createdAt: new Date().toISOString(),
    };
    persistSites([site, ...savedSites]);
    setSelectedSiteId(id);
    alert('Site saved to local storage ✅');
  };

  const loadSite = (id: string | null) => {
    if (!id) return;
    const site = savedSites.find((s) => s.id === id);
    if (site) {
      setEditableHtml(site.html);
      setSelectedSiteId(id);
      setShowCode(true);
    }
  };

  const deleteSite = (id: string) => {
    const remaining = savedSites.filter((s) => s.id !== id);
    persistSites(remaining);
    if (selectedSiteId === id) setSelectedSiteId(null);
  };

  const exportSites = () => {
    const blob = new Blob([JSON.stringify(savedSites, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'mini-app-factory-sites.json';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const importSites = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const data = JSON.parse(String(reader.result));
        if (Array.isArray(data)) {
          persistSites([...data, ...savedSites]);
          alert('Imported sites ✅');
        } else {
          alert('Invalid file format');
        }
      } catch {
        alert('Failed to import');
      }
    };
    reader.readAsText(file);
  };
  const downloadHTML = () => {
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/html;charset=utf-8,' + encodeURIComponent(editableHtml || html));
    element.setAttribute('download', 'website.html');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const downloadZip = async () => {
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      const content = editableHtml || html || '';
      zip.file('index.html', content);
      // Add a README
      zip.file('README.md', '# Generated Site\n\nGenerated by [Mini App Factory](https://github.com/Aditya190803/mini-app-factory)');
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'site.zip';
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Zip failed', err);
      alert('Failed to create ZIP');
    }
  };

  const runTransform = async () => {
    if (!transformPrompt.trim()) return;
    setIsTransforming(true);
    try {
      const response = await fetch('/api/transform', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: editableHtml || html, prompt: transformPrompt }),
      });
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Transform failed');
      }
      const data = await response.json();
      let updated = false;
      if (data.html) {
        setEditableHtml(data.html);
        updated = true;
      } else if (Array.isArray(data.files)) {
        const indexFile = data.files.find((file: { path: string; content: string }) => file.path === 'index.html');
        if (indexFile?.content) {
          setEditableHtml(indexFile.content);
          updated = true;
        }
      }
      if (!updated) {
        throw new Error('Transform returned no HTML output');
      }
      alert('Transformation applied ✅');
    } catch (err) {
      console.error('Transform error', err);
      alert('Transformation failed');
    } finally {
      setIsTransforming(false);
    }
  };

  return (
    <div 
      className="w-full md:w-1/2 flex flex-col border-l"
      style={{
        backgroundColor: 'var(--background)',
        borderColor: 'var(--border)',
      }}
    >
      <div 
        className="border-b flex items-center justify-between px-4 py-3 gap-3 backdrop-blur-sm"
        style={{
          backgroundColor: 'var(--background-overlay)',
          borderColor: 'var(--border)',
        }}
      >
        <div className="flex items-center gap-2">
          <button
            onClick={() => { setShowCode(false); setIsEditing(false); }}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold transition-all duration-200 border"
            style={{
              backgroundColor: !showCode ? 'var(--primary)' : 'transparent',
              color: !showCode ? 'var(--primary-foreground)' : 'var(--secondary-text)',
              borderColor: !showCode ? 'var(--primary)' : 'var(--border)',
            }}
          >
            PREVIEW
          </button>
          <button
            onClick={() => { setShowCode(true); }}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold transition-all duration-200 border"
            style={{
              backgroundColor: showCode ? 'var(--secondary)' : 'transparent',
              color: showCode ? 'var(--secondary-foreground)' : 'var(--secondary-text)',
              borderColor: showCode ? 'var(--secondary)' : 'var(--border)',
            }}
          >
            CODE
          </button>
          <button
            onClick={() => setIsEditing((v) => !v)}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold transition-all duration-200 border"
            style={{
              backgroundColor: isEditing ? 'var(--primary)' : 'transparent',
              color: isEditing ? 'var(--primary-foreground)' : 'var(--secondary-text)',
              borderColor: isEditing ? 'var(--primary)' : 'var(--border)',
            }}
          >
            {isEditing ? 'EDITING' : 'EDIT'}
          </button>
        </div>

        <div className="flex items-center gap-2">
          <select
            value={selectedSiteId ?? ''}
            onChange={(e) => { const id = e.target.value || null; setSelectedSiteId(id); loadSite(id); }}
            className="text-sm p-2 border"
            style={{ backgroundColor: 'var(--background-overlay)', borderColor: 'var(--border)', color: 'var(--secondary-text)' }}
          >
            <option value="">Saved Sites</option>
            {savedSites.map((s) => (
              <option key={s.id} value={s.id}>{s.name}</option>
            ))}
          </select>

          <button
            onClick={() => saveCurrentSite()}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
            style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
          >
            SAVE
          </button>

          <button
            onClick={downloadHTML}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
            style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
          >
            DOWNLOAD
          </button>

          <button
            onClick={downloadZip}
            className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
            style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
          >
            ZIP
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-auto">
        {html ? (
          showCode ? (
            <div className="p-6">
              <div className="flex gap-3 mb-4">
                <button
                  onClick={() => { navigator.clipboard.writeText(editableHtml || ''); alert('Copied to clipboard ✅'); }}
                  className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
                  style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
                >Copy</button>
                <button
                  onClick={() => saveCurrentSite()}
                  className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
                  style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
                >Save</button>
                <button
                  onClick={() => { setEditableHtml(html); alert('Reverted to generated HTML'); }}
                  className="px-3 py-1 text-xs font-mono uppercase font-semibold border"
                  style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
                >Reset</button>
              </div>

              {isEditing ? (
                <div className="border">
                  <CodeMirror
                    value={editableHtml}
                    height="420px"
                    onChange={(value) => setEditableHtml(value)}
                    basicSetup={{
                      highlightActiveLine: false,
                      defaultKeymap: true,
                    }}
                    theme="light"
                  />
                </div>
              ) : (
                <pre className="text-xs font-mono whitespace-pre-wrap break-words leading-relaxed" style={{ color: 'var(--secondary-text)' }}><code>{editableHtml}</code></pre>
              )}

              <div className="mt-4 grid grid-cols-1 md:grid-cols-4 gap-3 items-start">
                <input
                  value={transformPrompt}
                  onChange={(e) => setTransformPrompt(e.target.value)}
                  placeholder="Send a new prompt to the LLM to modify this site (e.g., 'Make the hero purple and add signup modal')"
                  className="col-span-2 p-3 text-sm border"
                  style={{ backgroundColor: 'var(--background-overlay)', borderColor: 'var(--border)', color: 'var(--secondary-text)' }}
                />
                <div className="flex gap-2">
                  <button
                    onClick={runTransform}
                    disabled={isTransforming}
                    className="px-3 py-2 text-xs font-mono uppercase font-semibold border"
                    style={{ backgroundColor: 'var(--primary)', color: 'var(--primary-foreground)', borderColor: 'var(--primary)' }}
                  >{isTransforming ? 'Applying...' : 'Apply LLM Prompt'}</button>
                  <button
                    onClick={async () => {
                      const desc = window.prompt('Provide a detailed polish description (images, typography, mobile, animations)');
                      if (!desc) return;
                      setIsTransforming(true);
                      try {
                        const resp = await fetch('/api/transform', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ html: editableHtml, polishDescription: desc }) });
                        if (!resp.ok) throw new Error('Polish failed');
                        const data = await resp.json();
                        let polishedContent: string | null = null;
                        if (data.html && typeof data.html === 'string' && data.html.trim()) {
                          polishedContent = data.html;
                        } else if (data.full && Array.isArray(data.files)) {
                          const indexFile = data.files.find((file: { path: string; content: string }) => file.path === 'index.html');
                          if (indexFile?.content && typeof indexFile.content === 'string' && indexFile.content.trim()) {
                            polishedContent = indexFile.content;
                          }
                        }
                        if (!polishedContent) {
                          console.error('Polish returned no usable HTML content', data);
                          throw new Error('Polish returned no content');
                        }
                        setEditableHtml(polishedContent);
                        alert('Polish applied ✅');
                      } catch (err) {
                        console.error(err);
                        alert('Polish failed');
                      } finally {
                        setIsTransforming(false);
                      }
                    }}
                    className="px-3 py-2 text-xs font-mono uppercase font-semibold border"
                    style={{ backgroundColor: 'var(--secondary)', color: 'var(--secondary-foreground)', borderColor: 'var(--secondary)' }}
                  >Polish Site</button>
                  <button
                    onClick={() => { const name = window.prompt('Optional site name'); if (name) saveCurrentSite(name); else saveCurrentSite(); }}
                    className="px-3 py-2 text-xs font-mono uppercase font-semibold border"
                    style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
                  >Save As...</button>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={exportSites}
                    className="px-3 py-2 text-xs font-mono uppercase font-semibold border"
                    style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}
                  >Export</button>
                  <label className="px-3 py-2 text-xs font-mono uppercase font-semibold border cursor-pointer" style={{ backgroundColor: 'transparent', color: 'var(--secondary-text)', borderColor: 'var(--border)' }}>
                    Import
                    <input type="file" accept="application/json" onChange={importSites} className="hidden" />
                  </label>
                </div>
              </div>

              {savedSites.length > 0 && (
                <div className="mt-6">
                  <h4 className="text-xs font-mono uppercase mb-2" style={{ color: 'var(--secondary-text)' }}>Saved Sites</h4>
                  <ul className="space-y-2">
                    {savedSites.map((s) => (
                      <li key={s.id} className="flex items-center justify-between p-3 border" style={{ backgroundColor: 'var(--background-overlay)', borderColor: 'var(--border)' }}>
                        <div>
                          <div className="text-sm font-semibold" style={{ color: 'var(--foreground)' }}>{s.name}</div>
                          <div className="text-xs" style={{ color: 'var(--secondary-text)' }}>{new Date(s.createdAt).toLocaleString()}</div>
                          {s.prompt && <div className="text-xs mt-1" style={{ color: 'var(--secondary-text)' }}>{s.prompt.length > 80 ? s.prompt.slice(0, 80) + '…' : s.prompt}</div>}
                        </div>
                        <div className="flex gap-2">
                          <button onClick={() => { setEditableHtml(s.html); setShowCode(true); setSelectedSiteId(s.id); }} className="px-2 py-1 text-xs border">Load</button>
                          <button onClick={() => { navigator.clipboard.writeText(s.html); alert('Copied'); }} className="px-2 py-1 text-xs border">Copy</button>
                          <button onClick={() => deleteSite(s.id)} className="px-2 py-1 text-xs border">Delete</button>
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ) : (
            <IframePreview html={editableHtml || html} />
          )
        ) : (
          <EmptyState />
        )}
      </div>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="h-full flex items-center justify-center flex-col gap-6 p-12">
      <div 
        className="w-20 h-20 flex items-center justify-center border text-4xl"
        style={{
          backgroundColor: 'var(--background-overlay)',
          borderColor: 'var(--border)',
          color: 'var(--primary)',
        }}
      >
        ⚡
      </div>
      <div className="text-center">
        <h3 
          className="text-base font-display font-black uppercase tracking-tight mb-2"
          style={{ color: 'var(--foreground)' }}
        >
          Ready to Fabricate
        </h3>
        <p 
          className="text-sm max-w-xs leading-relaxed font-sans"
          style={{ color: 'var(--secondary-text)' }}
        >
          Describe your website on the left panel and click Generate to see your fabricated design here.
        </p>
      </div>
    </div>
  );
}

function IframePreview({ html }: { html: string }) {
  return (
    <div className="w-full h-full bg-white">
      <iframe
        srcDoc={html}
        className="w-full h-full border-0"
        sandbox="allow-scripts allow-same-origin allow-forms"
        title="Website Preview"
      />
    </div>
  );
}

