import { generateText } from "ai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { createGroq } from "@ai-sdk/groq";
import { buildReadmePrompt } from "@/lib/site-builder";

const FALLBACK_ATTRIBUTION = "Made by [Mini App Factory](https://github.com/Aditya190803/mini-app-factory)";

function cleanRepoDescription(text: string, maxLength = 160): string {
  const cleaned = text
    .replace(/[\u0000-\u001F\u007F]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (cleaned.length <= maxLength) return cleaned;
  return cleaned.slice(0, maxLength).replace(/\s+\S*$/, "").trim();
}

async function generateWithFallback(prompt: string): Promise<string> {
  const googleKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  const groqKey = process.env.GROQ_API_KEY;

  if (googleKey) {
    const google = createGoogleGenerativeAI({ apiKey: googleKey });
    const { text } = await generateText({
      model: google(process.env.GOOGLE_MODEL || "gemini-3-flash-preview"),
      prompt,
    });
    return text;
  }

  if (groqKey) {
    const groq = createGroq({ apiKey: groqKey });
    const { text } = await generateText({
      model: groq(process.env.GROQ_MODEL || "moonshotai/kimi-k2-instruct-0905"),
      prompt,
    });
    return text;
  }

  return "";
}

export async function generateReadmeContent(opts: {
  projectName: string;
  prompt: string;
  files: string[];
}): Promise<string> {
  const { projectName, prompt, files } = opts;
  const readmePrompt = buildReadmePrompt(projectName, prompt, files);

  try {
    const content = await generateWithFallback(readmePrompt);
    if (content.trim()) return content;
  } catch (error) {
    console.error("README generation failed:", error);
  }

  return `# ${projectName}\n\n${prompt}\n\n---\n${FALLBACK_ATTRIBUTION}`;
}

export async function generateRepoDescription(opts: {
  projectName: string;
  prompt?: string;
  files?: string[];
}): Promise<string> {
  const trimmedPrompt = opts.prompt?.trim() || "";
  const fallback = cleanRepoDescription(trimmedPrompt || "Generated by Mini App Factory");

  if (!trimmedPrompt) {
    return fallback;
  }

  const descriptionPrompt = `Write a concise GitHub repository description (max 160 characters) for a project named "${opts.projectName}".
Prompt: "${trimmedPrompt}"
Included files:
${(opts.files || []).map((file) => `- ${file}`).join("\n")}

Rules:
- Output plain text only.
- No quotes, no markdown, no emojis.
- Keep it specific and compelling, under 160 characters.`;

  try {
    const text = await generateWithFallback(descriptionPrompt);
    if (!text.trim()) return fallback;
    return cleanRepoDescription(text, 160) || fallback;
  } catch (error) {
    console.error("Repo description generation failed:", error);
    return fallback;
  }
}
