import 'server-only';

import { getAIClient } from "@/lib/ai-client";

const FALLBACK_ATTRIBUTION = "Made by [Mini App Factory](https://github.com/Aditya190803/mini-app-factory)";

function buildReadmePrompt(projectName: string, description: string, files: string[]): string {
  // Callers only have paths here, so this mirrors the path rules in `inferTarget`.
  const isEdgeApp = files.some(
    (f) =>
      f === "_worker.js" ||
      f.startsWith("workers/") ||
      f.startsWith("migrations/") ||
      f === "cloudflare.manifest.json"
  );
  const runInstructions = isEdgeApp
    ? "How to run it: this is a Cloudflare edge app (a Worker plus declared bindings), so explain running it locally with `npx wrangler pages dev .` and deploying with `npx wrangler pages deploy .`, and list the bindings from cloudflare.manifest.json that must exist first."
    : "How to preview it: open index.html in a browser, or deploy the folder as-is to Cloudflare Pages with `npx wrangler pages deploy .`.";

  return `Create a high-quality, professional README.md file for the project: "${projectName}".

Context:
This project was generated based on the following prompt: "${description}"

Included files:
${files.map((f) => `- ${f}`).join("\n")}

The README should include:
1. A clear project title.
2. A compelling project description based on the prompt.
3. Features list (infer from the prompt and files).
4. Project structure overview.
5. ${runInstructions}

Final line requirement:
The very last line of the README must be exactly:
"${FALLBACK_ATTRIBUTION}", preceded by a horizontal rule.

Output only the Markdown content for the README.md file. No preamble or conversational filler.`;
}

function cleanRepoDescription(text: string, maxLength = 160): string {
  const cleaned = text
    .replace(/[\u0000-\u001F\u007F]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (cleaned.length <= maxLength) return cleaned;
  return cleaned.slice(0, maxLength).replace(/\s+\S*$/, "").trim();
}

async function generateWithFallback(prompt: string): Promise<string> {
  const session = await (await getAIClient()).createSession();
  try {
    return (await session.sendAndWait({ prompt })).data.content;
  } finally {
    await session.destroy();
  }
}

export async function generateReadmeContent(opts: {
  projectName: string;
  prompt: string;
  files: string[];
}): Promise<string> {
  const { projectName, prompt, files } = opts;
  const readmePrompt = buildReadmePrompt(projectName, prompt, files);

  try {
    const content = await generateWithFallback(readmePrompt);
    if (content.trim()) return content;
  } catch (error) {
    console.error("README generation failed:", error);
  }

  return `# ${projectName}\n\n${prompt}\n\n---\n${FALLBACK_ATTRIBUTION}`;
}

export async function generateRepoDescription(opts: {
  projectName: string;
  prompt?: string;
  files?: string[];
}): Promise<string> {
  const trimmedPrompt = opts.prompt?.trim() || "";
  const fallback = cleanRepoDescription(trimmedPrompt || "Generated by Mini App Factory");

  if (!trimmedPrompt) {
    return fallback;
  }

  const descriptionPrompt = `Write a concise GitHub repository description (max 160 characters) for a project named "${opts.projectName}".
Prompt: "${trimmedPrompt}"
Included files:
${(opts.files || []).map((file) => `- ${file}`).join("\n")}

Rules:
- Output plain text only.
- No quotes, no markdown, no emojis.
- Keep it specific and compelling, under 160 characters.`;

  try {
    const text = await generateWithFallback(descriptionPrompt);
    if (!text.trim()) return fallback;
    return cleanRepoDescription(text, 160) || fallback;
  } catch (error) {
    console.error("Repo description generation failed:", error);
    return fallback;
  }
}
